### ISSUE TITLE
it can support PMSM?

### ISSUE THREAD

**Issue by Alvazz** [ThoMint/modFOC#1]
Hi,
this FOC controller, it can support PMSM motor or not?

**Comment by ThoMint** [comment]
Hello,
Yes it can however i would recommend to wait for the next revision if your planning on building this Motion Controller yourself.
Next Version will also support Stepper and other encoder types. There will also be a configuration desktop app.

**Comment by Alvazz** [comment]
Thank you for your reply, I look forward to it
